### ISSUE TITLE
Ingest Node - Grok Processor

### ISSUE THREAD

**Issue by christopherfriedrich** [opendistro-for-elasticsearch/sample-code#239]
Hi guys,

i am trying to transform my documents in opendistro elasticsearch with an ingest pipeline with a grok processor (i also enabled the security feature and use the admin user for everything). So i created a pipeline using the REST API (PUT _ingest/pipeline/my-pipeline) and configured filebeat to use this pipeline:

```yaml
output:
    elasticsearch:
       …
       pipeline: my-pipeline
       …
```

But when watching the documents, they are not transformed, and it seems like the pipeline is ignored.
Filebeat connects to the elasticsearch container and the logs are shown there but the transformation was not executed.
I tested it with the elastic-oss image and it works there.
Any ideas?
